[pytest]
addopts = -p no:asyncio
markers =
    device: device-level integration tests
    smoke: smoke test suite
    regression: regression test suite
    ui: UI tests
    order: execution order of tests
pythonpath = .

[tool:pytest]
asyncio_mode = auto
markers =
    order: execution order of tests
filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning:urllib3.connectionpool

[tool:pytest-playwright]
browser_name = chromium
launch_args = ["--start-maximized"]